# Present benchmark results as a comment on the PR
# Taken and adapted from https://github.com/rhysd/github-action-benchmark/blob/master/.github/workflows/pytest.yml
name: Benchmark
on:
  # only run on pull requests again the main branch
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: Run pytest-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r test-requirements.txt
      - name: Run benchmark
        run: |
          cd tests
          pytest benchmark.py --benchmark-min-rounds=4 --benchmark-only -n 0 --no-cov --benchmark-json output.json
      - name: Download artifact of previous benchmarks from default branch
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: benchmark_default_branch.yml
          name: benchmark_results
          path: old_benchmark
          commit: ${{github.event.pull_request.base.sha}}
        continue-on-error: true
      - name: Publish results as comment
        uses: nils-braun/pytest-benchmark-commenter@v2
        with:
          benchmark-file: tests/output.json
          comparison-benchmark-file: "old_benchmark/output.json"

