---
name: Python Style Check
on: [pull_request]
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: pycodestyle
        uses: ankitvgupta/pycodestyle-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRECOMMAND_MESSAGE: You have style errors. See them below.
