---
name: Test Default Branch
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}

    - name: Install dependencies
      run: |
        # Do all the installations
        python -m pip install --upgrade pip wheel setuptools
        pip uninstall tsfresh
        pip install -r requirements.txt -r test-requirements.txt
        pip install .

        # Print out the pip versions for debugging
        pip list

    - name: Test with pytest
      run: |
        # Include notebook tests
        rm -rf .coverage.*
        export TEST_NOTEBOOKS=y
        pytest --junitxml=junit/test-results.xml --cov-report=xml tests

    - name: Upload pytest test results
      uses: actions/upload-artifact@v1
      with:
        name: pytest-results
        path: junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
